<?php

namespace CovoiturageBundle\Repository;

/**
 * AnnonceCovoiturageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceCovoiturageRepository extends \Doctrine\ORM\EntityRepository
{
}
