<?php

namespace CovoiturageBundle\Repository;

/**
 * AnnonceCoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceCoRepository extends \Doctrine\ORM\EntityRepository
{
}
